### ISSUE TITLE
Header filter syntax

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#1154]
We could use a header-filter syntax, with query pathes and functions and so on:

# Usecase

`imag find --header 'links.internal.count() > 3'`

Finds and lists all entries which have more than 3 links.

# Scope

The **Scope** is _only_ to be able to get values from `toml::Value` objects. That's also why we could move this to a (imag independent) crate. We do **not** want to be able to alter contents of the store here.

# Required functionality

- [x] TOML value querying (provided by `toml-query` crate)
- [ ] Types
- [ ] Operators
- [ ] Functions to be applied on `Value` objects

## Our DSL must provide some basic types

- [ ] Integers
- [ ] Floats
- [ ] Booleans
- [ ] Strings
- [ ] `toml::Value` must be passed through

## Operators

As the whole point is to write filters, we must always return a boolean value. So basic operators are enough here:

- [ ] `not`
- [ ] `and`
- [ ] `or`
- [ ] `xor`

## Functions

- [ ] Functions for `Vec<_>` / `Value::Array`
    - [ ] `at(idx)` / `[idx]` returning Value
    - [ ] `len()` / `count()` returning integer
    - [ ] `contains(value)` / `has(value)` returning boolean. The `value` parameter must be able to be infered to either `Value` or a primitive type
- [ ] Functions for `Value::Table` and `BTreeMap`/`HashMap`
    - [ ] `keys()` / `values()` for `Value::Table` returning `Vec<Value>`
    - [ ] `exists(key)` returning boolean
    - [ ] `at(key)` / `[key]` returning `Value`
- [ ] Functions for String type
    - [ ] `contains(substr)` returning boolean
    - [ ] `match(str-regex)` using the provided string as regex for matching, returning boolean
    - [ ] `grep(str-regex)` using the provided string as regex, returning matched substring
    - [ ] `len()` returning integer
    - [ ] `substr(start, end)` returing the substr from `start..end`

# Implementation

Most of the things we described here are provided by the `filters` and the `toml-query` crate. Although this whole idea here would be awesome to be implemented in a (imag independent) crate. If not, I would still put this into a new imag crate.

One could use `nom` or `rust-peg` to implement the syntax, so the whole thing should be rather straight-forward. I'd opt for `rust-peg` because it features a nice grammar file approach for describing the syntax, which is nice, but on the other hand one needs a build-script for using it. So, not sure whether rust-peg is a nice idea,...

# Using already implemented DSLs?

I am not sure whether we could simply use a DSL which is already implemented.

Lets discuss the options

## [Dyon](https://github.com/PistonDevelopers/dyon)

Nice Syntax, good support I suppose (because piston developers). Although a bit complex for our needs (as in syntax).

## [Ketos](https://github.com/murarth/ketos)

Not sure whether we really want a LISP here. Also: Is the project still active?

## [hlua](https://github.com/tomaka/hlua)

Lua seems to be too complex (as in syntax) for simple filter scripts, right? On the other hand it is fast and as far as I know easy to use.

# Old discussions

We already had an issue for this [here](https://github.com/matthiasbeyer/imag/issues/245), though the scope is a bit different right now.

**Comment by matthiasbeyer** [comment]
#1468 starts implementing this. It implements a functionality to filter in `imag-ids`. The functionality does only cover header value filtering, but we could move this out of the crate and provide a much more extended syntax and functionality later on... it's a first step.

**Comment by matthiasbeyer** [comment]
Because we are now [moving off of github](https://github.com/matthiasbeyer/imag/pull/1505) I'm closing this PR/Issue now. The reasons why we do this was described in a [blogpost](https://imag-pim.org/blog/2018/06/10/off-of-github/). Feel free to resubmit this PR/Issue via the mailinglist.
