### ISSUE TITLE
Rewrite libimagentryref

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#1284]
We need to rewrite `libimagentryref` because its purpose changed slightly in the past months of development.

# Purpose / Incentive

`libimagentryref` provides "references" to files on the filesystem. A reference might be used by a domain library to refer to data outside of the store (like libimagcontact refers to vcard files without putting them into the store). A reference might not be only a "reference entry" in the store but rather a more complex entry which _contains_ a reference. Thus, libimag_entry_ref is the right name for this library and it should only provide a building block for the actual entry.

# API Requirements

- [x] A way to generate reference names (for example a SHA1 hash) which can then be used to build an actual `StoreId` from, under a custom collection. So basically a `UniqueFileIdGenerator`.
- [ ] A way to re-find files via a custom `FileFinder` that implements its own filesystem traversal (and can thus filter for certain filetypes or even whether something is actually a file or a directory)
- [ ] A way to get the actual file with automatic integrity checking (whether it still matches the `UniqueFileId` which was stored for the file).

# Impact

Currently the following crates depend on `libimagentryref` and need probably to be rewritten for this:

- [ ] `imag-ref`
- [x] `libimagcontact`
- [ ] `imag-contact`
- [x] `libimagmail`
- [x] `libimagentrymarkdown`

It will also influence how `libimagcalendar` will be implemented.
