### ISSUE TITLE
Enable certain compiler warning-as-error flags

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#189]
@TheNeikos I'm not sure when we want to do this, but I guess as soon as possible, right?

We want:

- [ ] `unused_return`
- [ ] `missing_docs`
- [ ] `missing_copy_implementations`
- [ ] `trivial_casts`
- [ ] `trivial_numeric_casts`
- [ ] `unsafe_code`
- [ ] `unstable_features`
- [ ] `unused_import_braces`
- [ ] `unused_qualifications`
- [ ] `unused_code`
- [ ] `dead_code`

(each of them should go into a seperated PR)

and maybe some more from https://github.com/rust-lang/rust/blob/master/src/librustc/lint/builtin.rs

We might also add https://github.com/huonw/spellck (it seems to be out of date, though it might work) and/or https://crates.io/crates/clippy

**Comment by TheNeikos** [comment]
I would also like to add clippy, so +1 on that

**Comment by matthiasbeyer** [comment]
I will close this now, as almost all crates have lints enabled and do these checks already.
