### ISSUE TITLE
[counter] Add counting backends

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#254]
We should change the counting algorithm to collect dates of increments, decrements and so on.

This way one could easily extract historical data from the counter.

---

Edit: This is and should be even more complex. 

# Counting Backends

I think we should add different counting backends. Such a backend defines how certain thinks work. I think of a trait like this:

```rust
pub trait CountingBackend {
    fn inc_n(&self, &mut Entry, u64) -> Result<(), CountingBackendError>;
    fn inc(&self, e: &mut Entry) -> Result<(), CountingBackendError> {
        self.inc_n(e, 1)
    }
    fn dec_n(&self, &mut Entry, u64) -> Result<(), CountingBackendError>;
    fn dec(&self, e: &mut Entry) -> Result<(), CountingBackendError> {
        self.dec_n(e, 1)
    }
    fn count(&self, &Entry) -> Result<i64, CountingBackendError>;
    fn reset(&self, &mut Entry) -> Result<(), CountingBackendError>;
}
```

This trait could then be implemented for some builtin backends:

- [ ] `DefaultCountingBackend` - which just writes the current number into a header field - the `Counter` should contain the `DefaultCountingBackend` by default
- [ ] `TimeCountingBackend` - Which records each inc/dec with a timestamp
- [ ] `DateCountingBackend` - Which records each inc/dec with a date
- [ ] possibly more

The backend would be passed to the `Counter` object by template argument and the `Counter` should instantiate the backend on its own, if such a thing is possible (maybe @TheNeikos can tell).

---

The data collected by such counters could later be used to export the data in a fancy way, for example CSV or JSON, and be processed using tools like gnuplot or such (not covered by imag, of course).

**Comment by matthiasbeyer** [comment]
I will close this now as wont-implement.
