### ISSUE TITLE
Add Runtime::editor() which helps opening files

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#259]
@asuivelentine wanna do this? It's an rather easy one.

- [ ] Add a function `Runtime::editor(&self) -> Command`
  - [ ] Read the current Edior from config file
  - [ ] Read the current Editor from CLI
  - [ ] Read the current Editor from env
  - [ ] Create a `std::process::Command` instance and return it

**Comment by matthiasbeyer** [comment]
Would be more feasible to return `-> Result<Command, RuntimeError>`
