### ISSUE TITLE
Rewrite libimaglink - external linking

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#300]
We should rewrite the `libimaglink` external linking module to

- [ ] Generate Entries in the store under `/external-link` where each entry links to one URL
- [ ] Allow linking operations on `Entry` objects:
  - [ ] linking an external link by putting the actual link into `/external-link/<something>` and linking this new entry with an internal link
  - [ ] listing external links for one entry
  - [ ] listing Entries which are linked from one external link (as internal linking is two-way-linking)

This would contain API changes of the `external` module in `libimaglink` and of course `imag-link` should be adapted.
