### ISSUE TITLE
[module]: Bookmarks

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#301]
The bookmark module should contain this functionality (all functionality should be offered by the library, the binary should only implement a user interface for it):

- [x] Adding a bookmark
  - [x] With URL (required)
  - [ ] With tags (optional, using `libimagtag`)
- [ ] Tagging a bookmark
  - [ ] By filtering all bookmarks for (using `libimagentryfilter`)
    - [ ] Already existing tags (using `libimagtag`)
    - [ ] URL `grep`
    - [ ] URL `startswith`
  - [ ] By hash (see "listing bookmarks")
- [x] Listing bookmarks (using `libimagentrylist`, `libimagentryfilter`)
  - [ ] With fields:
    - [ ] "hash" which should be an abbreviated Hash (SHA1 / SHA512... ?) over the URL (optional, configure via CLI)
    - [x] The actual URL 
    - [ ] The tags (using `libimagtag`, optional, configure via CLI)
- [x] Deleting bookmarks by (using `libimagentryfilter`)
  - [ ] Hash
  - [ ] Tags (using `libimagtag`)
  - [ ] URL `grep`
  - [ ] URL `startswith`
- [ ] Opening all bookmarks via `xdg-open`, filtered by (using `libimagentryfilter`)
  - [ ] Hash
  - [ ] Tags (using `libimagtag`)
  - [ ] URL `grep`
  - [ ] URL `startswith`

---

This Issue is doable as soon as the following PRs have landed:

- [x] #267 
- [x] #300 

---

I'll mark this issue `easy`, as it does not include complex code parts IMO. A PR would be still a rather _big_ PR, though not complex code-wise.

**Comment by matthiasbeyer** [comment]
WIP in #521 and #522

**Comment by matthiasbeyer** [comment]
Reopened as the merge of #521 closed this but the merge of #522 should close it.

The features from the top-level comment are not yet included and just a basis-set of features is included, ...
