### ISSUE TITLE
[module]: imag-stat

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#306]
A simple module which generates some diagnostics about the store.

Could also be named `imag-diagnostics` or `imag-diags`.

Some possible stats:
- [ ] Number of entries
- [ ] Number of entries per collection/module (percentage?)
- [ ] Tags and numbers of entries tagged with each tag
- [ ] Internal links
  - [ ] overall
  - [ ] dead
- [ ] External links
- Average text size of entries
- Average text size of entries with content
- Largest entry
- Maybe even printing graphs

etc etc.

---

We should probably use the [tui](https://github.com/fdehau/tui-rs) crate for this. But I wonder how much it can be used to integrate it into a `Cursive` backed TUI.

**Comment by matthiasbeyer** [comment]
I would actually use this as a playground for optional compiling. I would not include this in imag per default. We could implement this as feature of `libimagrt` and switch off by default.

Calling `imag stats` or `imag diagnostics` would yield `No diagnostic support compiled into imag` per default, and if it is compiled into imag print a standard-set (non-configurable) by calling functions in the store, the runtime object and so on ...
