### ISSUE TITLE
[module]: weather

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#317]
I'm planning to include a weather module.
# Ideas for features

What this module should be able to do:
- [ ] Get weather data from <somewhere>
- [ ] Persist the weather data in the store, so we can
  - [ ] link to the weather data
  - [ ] print stats about weather data maybe?
- [ ] Tell the weather for <time> and <location>, if the time points to the future, we want a forecast, if it points to the past we want to query either the store or an online service for historical data
  - [ ] in offline mode (aka. if the data is already in the store)
  - [ ] by querying some service
- [ ] forecasting by
  - [ ] `N` days, weeks
  - [ ] location

---

What would be awesome: If it would support multiple backends (as there are a lot of tools out there for doing weather foo). For the first step it would be enough to use [wego](https://github.com/schachmat/wego), which has a JSON frontend we could use to import data.

This would be a rather simple task, I think.

If we support openweathermap later on, this would be awesome! Not necessarily by implementing a client for OWM, but by using another tool.

---
# File Path

The format in which the data is stored should be something like this:

```
/weather/<year>-<month>-<day>/<location>-<hour>-<minute>
```

or

```
/weather/<location>/<year>-<month>-<day>/<hour>-<minute>
```

I'm not sure how to encode `<location>`. Maybe using Longitude and Latitude, maybe using city names (I'd prefer the former).
# Data Format

The data should be stored in the entry header, of course. We need _many_ fields, to be able to support different service backends (OWM, wego... etc).

Brain-dump of fields we want:
- Temperature (should be stored in Kelvin and transformed for user-viewing, IMO)
- Wind (direction, strength...)
- Cloudiness (in words? I'm not sure)
- Pressure
- Humidity
- Sunrise Time
- Sunset Time

Maybe more?

**Comment by schachmat** [comment]
Just linking schachmat/wego#84 here. An openweathermap backend is also planned.

**Comment by schachmat** [comment]
wego has a json backend now, so you can run `wego -frontend json >/path/to/storage/file` to save the current data and `wego -backend json /path/to/storage/file` to display the cached data.

**Comment by matthiasbeyer** [comment]
@schachmat awesome, thank you!

**Comment by matthiasbeyer** [comment]
Because we are now [moving off of github](https://github.com/matthiasbeyer/imag/pull/1505) I'm closing this PR/Issue now. The reasons why we do this was described in a [blogpost](https://imag-pim.org/blog/2018/06/10/off-of-github/). Feel free to resubmit this PR/Issue via the mailinglist.
