### ISSUE TITLE
libimagentryview: Add JSON viewer

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#467]
We could add a JSON viewer which does the following:
- [ ] Translate the Header to JSON
- [ ] Put the Header in a `{ header: <HEADER> }`
- [ ] Put the content in a `{ content: <CONTENT> }`
- [ ] Print the whole thing as JSON
- [ ] Allows to print a JSON array of JSON objects

**Comment by matthiasbeyer** [comment]
If the request in https://github.com/alexcrichton/toml-rs/issues/106 fails we have to implement the first point ourselves.

**Comment by matthiasbeyer** [comment]
As of right now, this is possible with the new store backend switching. So I'll close this. Also because this is not and shouldn't be our focus right now.
