### ISSUE TITLE
[testing]: Refactor, so we can test the application as a whole

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#48]
We would need to refactor the application into a library and a binary, whereas the binary uses the library. As we pass around the `ArgMatches` object from `clap` at the moment, such a change would result in a large refactoring step.

- [ ] Introduce types which represent CLI values
- [ ] Remove `clap`-code from the module codebase
- [ ] Unify the module calling code (or provide enough abstraction)
- [ ] Introduce tests for module actions

**Comment by TheNeikos** [comment]
What do you mean by `CLI values`?

**Comment by matthiasbeyer** [comment]
Well, I'm passing around an `ArgMatches` type, which is a type from `clap`. To be able to test the application, we have to get rid of the `clap` dependency inside the module code. Therefor we have to introduce types which represent the commandline call as parsed with `clap`, but which do not depend on `clap` code internally.

This way we can "simulate" commandline calls (via own types) to the library and use these types for testing instead of parsing clap results.

**Comment by TheNeikos** [comment]
I see, well if you don't mind me taking some more time I wouldn't mind checking it out. Since I am working currently I don't have as much free time as I would like.

**Comment by matthiasbeyer** [comment]
So you wanna do this? Nice! I don't mind if this takes longer! I want a testable application in 0.1.0, and by now there are releases up to 0.0.7 planned and I guess there will be at least releases until 0.0.10 or something, so no problem with this taking a bit longer.

Either way, you have to keep up with the master, as I'm going to add more code in the modules in the next days, so you might have to rebase and fixup rather often, but that's life!

**Comment by TheNeikos** [comment]
Yeah that's fine by me

**Comment by matthiasbeyer** [comment]
This issue will be closed now, as it was created for pre-reset imag code.
