### ISSUE TITLE
Rewrite Runtime

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#83]
The `Runtime` type could be reused almost completely, anyways the `CLI` type would be partly rewritten, which is what the `Runtime` type depends on.

- [ ] CLI-Type rewrite
  - [ ] Flag handling
    - [ ] verbosity
    - [ ] debugging
  - [ ] configuration file setter
- [ ] Configuration file parsing (Move to TOML)
- [ ] Should hold the Store interface object
