### ISSUE TITLE
imag-habit: Habit tracker

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#948]
Another idea for an imag-tool: A habit tracker.

- [x] Defining habits
  - [x] Iteration: Daily, weekly, monthly
  - [ ] With a "habit-question": "Did you drink enough today?" (user-defined)
- [x] One can "check off" a habit
- [ ] Generating of statistics 

[more to come]

---

Inspired by [Loop Habit Tracker](https://f-droid.org/repository/browse/?fdfilter=loop&fdid=org.isoron.uhabits)
